#Workflow to build react app on pull request, then test it, if pass tests, open issue for manual approval

name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test react app
    runs-on: ubuntu-latest

    inputs:
      who-to-greet:
        description: "Who to greet"
        required: true
        default: "Elvis"

    outputs:
      dad-joke:
        description: "The dad joke"

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
        id: test
        outputs:
          test-result: ${{ steps.test.outputs.test-result }}

      - name: Create Issue
        if: ${{ success() }}
        run: |
          echo "Creating issue, manual approval required"
          gh issue create --title "PR Passed Tests, Need Approval" --body "approve then deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #code to run custom javascript file
      - name: Run index.js
        run: node index.js
        needs: [Test]
        with:
          test-result: ${{ needs.Test.outputs.test-result }}
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
        id: dad-joke
